M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu20.04.1} date 2024-08-15T08:25:24-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-15T08:25:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X5.9236Y-4.0071
X6.6913Y-4.0071
M30
